export const wordsData = [
	['lenni', 'be'],
	['vmivé válni', 'become'],
	['elkezdeni', 'begin'],
	['harapni', 'bite'],
	['vérezni', 'bleed'],
	['törni, összetörni', 'break'],
	['hozni', 'bring'],
	['építeni', 'build'],
	['égetni', 'burn'],
	['vásárolni', 'buy'],
	['elkapni', 'catch'],
	['választani', 'choose'],
	['főzni', 'cook'],
	['jönni', 'come'],
	['ára vminek', 'cost '],
	['vágni', 'cut'],
	['csinálni', 'do'],
	['házi feladatot írni', 'do homework'],
	['rajzolni', 'draw'],
	['inni', 'drink'],
	['vezetni', 'drive'],
	['enni', 'eat'],
	['esni', 'fall'],
	['etetni', 'feed'],
	['érezni', 'feel'],
	['harcolni', 'fight'],
	['találni', 'find'],
	['repülni', 'fly'],
	['elfelejteni', 'forget'],
	['fagyasztani', 'freeze'],
	['kapni', 'get'],
	['felkelni', 'get up'],
	['felöltözni', 'get dressed'],
	['adni', 'give'],
	['menni', 'go'],
	['úszni menni', 'go to swim'],
	['nőni', 'grow'],
	['akasztani', 'hang'],
	['birtokolni', 'have'],
	['reggelizni', 'have breakfast'],
	['ebédelni', 'have lunch'],
	['vacsorázni', 'have dinner'],
	['zuhanyozni', 'have a shower'],
	['hallani', 'hear'],
	['elrejteni, elbújni', 'hide'],
	['megütni', 'hit'],
	['tartani', 'hold'],
	['bántani', 'hurt'],
	['tartani', 'keep'],
	['tudni', 'know'],
	['tanulni', 'learn'],
	['hagyni, elhagyni', 'leave'],
	['kölcsönözni', 'lend'],
	['hagyni', 'let'],
	['feküdni', 'lie'],
	['hazudni', 'lie'],
	['lefektetni, fektetni', 'lay'],
	['szeretni, kedvelni', 'like'],
	['elhagyni', 'lose'],
	['szeretni', 'love'],
	['csinalni, készíteni', 'make'],
	['jelenteni', 'mean'],
	['találkozni', 'meet'],
	['fizetni', 'pay'],
	['játszani', 'play'],
	['focizni', 'play football'],
	['tenni', 'put'],
	['olvasni', 'read'],
	['lovagolni', 'ride'],
	['biciklizni', 'ride a bike'],
	['csengeni', 'ring'],
	['futni', 'run'],
	['mondani', 'say'],
	['látni', 'see'],
	['eladni', 'sell'],
	['küldeni', 'send'],
	['mutatni', 'show'],
	['énekelni', 'sing'],
	['ülni', 'sit'],
	['aludni', 'sleep'],
	['beszélni', 'speak'],
	['betűzni', 'spell'],
	['elkölteni', 'spend'],
	['állni', 'stand'],
	['lopni', 'steal'],
	['úszni', 'swim'],
	['elvenni', 'take'],
	['fotózni', 'take a photo'],
	['kutyát sétáltatni', 'take the dog for a walk'],
	['tanítani', 'teach'],
	['elmondani', 'tell'],
	['gondolkodni', 'think'],
	['eldobni', 'throw'],
	['utazni', 'travel'],
	['érteni', 'understand'],
	['ébredni', 'wake'],
	['akarni', 'want'],
	['viselni', 'wear'],
	['győzni', 'win'],
	['írni', 'write'],
];
